--- 
## Lines that must be updated when we release a new software version are indicated in comments below


output_dir: output
staging_deploy_root: biocadmin@merlot2.fhcrc.org:/loc/www/bioconductor-test.fhcrc.org
production_deploy_root: webadmin@krait:/extra/www/bioc
## CHANGE THIS WHEN WE RELEASE A VERSION:
release_version: "2.14"
r_version_associated_with_release: "3.1.0"
## CHANGE THIS WHEN WE RELEASE A VERSION:
devel_version: "3.0"
## CHANGE THIS WHEN WE ADD A VERSION:
## this is the list of all versions for which we want to generate "new" bioc-views, package
## index, and package detail pages
versions:
## if old versions (no older than 2.5) need to be rebuilt for any reason,
## add them here, but in most cases this should just contain the
## release and devel versions:
- "2.14"
- "3.0"
## CHANGE THIS as various parts of the new devel version become available.
## set to "[]" if none are available.
devel_repos:
- "bioc"
- "data/experiment"
- "data/annotation"
## CHANGE this when the build machines change:
## also, don't include machines that are not building yet (comment them out)
active_devel_builders:
  linux: "zin1"
  windows: "moscato1"
  mac: "perceval"
active_release_builders:
  linux: "zin2"
  windows: "moscato2"
  mac: "petty"
rss_hub_url: "https://pubsubhubbub.appspot.com/"
## CHANGE these as AMI IDS change
ami_ids:
 bioc2_8: ami-3a2ef452
 bioc2_9: ami-2623f94e
 bioc2_10: ami-5621fb3e
 bioc2_11: ami-f827fd90
 bioc2_12: ami-7224fe1a
 bioc2_13: ami-4a25ff22
 bioc2_14: ami-9c25fff4
 bioc3_0: ami-36338f5e
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
  encoding: utf-8
  config:
    encoding: utf-8
- items_root: /mailing-list-posts
  type: biostar_list
  encoding: utf-8
  config:
    gmane_rss_url: 'http://rss.gmane.org/messages/excerpts/gmane.science.biology.informatics.conductor'
    cache_file: tmp/gmane_list_cache_file.yaml
    encoding: utf-8
    ttl: 10
- items_root: /help/bioc-views/package-pages
  layouts_root: /
  type: bioc_views
  encoding: utf-8
  config:
    json_dir: "assets/packages/json"
    encoding: utf-8
# CHANGE THIS when it becomes apparent which future versions of BioC will
# work with which versions of R:
r_ver_for_bioc_ver: 
  "1.6": "2.1"
  "1.7": "2.2"
  "1.8": "2.3"
  "1.9": "2.4"
  "2.0": "2.5"
  "2.1": "2.6"
  "2.2": "2.7"
  "2.3": "2.8"
  "2.4": "2.9"
  "2.5": "2.10"
  "2.6": "2.11"
  "2.7": "2.12"
  "2.8": "2.13"
  "2.9": "2.14"
  "2.10": "2.15"
  "2.11": "2.15" # R switching to yearly releases, BioC remaining the same
  "2.12": "3.0"
  "2.13": "3.0"
  "2.14": "3.1"
  "3.0": "3.1"
  "3.1": "3.2"
  "3.2": "3.2"
  "3.3": "3.3"
  "3.4": "3.3"
  "3.5": "3.4"
